name: spot
description: "A new Flutter project."

# Impede que o pacote seja publicado no pub.dev. Remova esta linha para publicar.
publish_to: 'none'

# Definição da versão e número de build da aplicação.
version: 1.0.0+1

# Define a versão mínima do SDK do Dart que será utilizada.
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependência para ícones no estilo Cupertino (iOS).
  cupertino_icons: ^1.0.8

# Dependências para o ambiente de desenvolvimento e testes.
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Conjunto recomendado de lint rules para boas práticas de código.
  flutter_lints: ^5.0.0

flutter:
  # Garante a inclusão da fonte de ícones de material design.
  uses-material-design: true

  # Seção para incluir assets (exemplo comentado).
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Exemplo para adição de fontes personalizadas.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
